//encapsulation - binding data with method
public class TwentySevEncapsulationC {  //consider as student class
	
	private int rollno;
	private String name;
	public int getRollno() {
		System.out.println("user is accesing ghe value");
		return rollno;
	
	}
	public void setRollno(int rollno) { //can be generated by eclipse
		this.rollno = rollno;
		System.out.println("Value of rollno. is changed");
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	//getters and setters
	
//	public void setRollno(int r)
//	{
//		rollno = r;
//		
//	}
//	public int getRollno(int r){
//		return rollno;
//	}

}
